name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu:22.04

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag my-image-name:$(date +%s)
        echo "${{ secrets.DOCKERPW }}" | docker login -u "flerich" --password-stdin
        docker image build -t flerich/proyectom2:v1 .
        docker push flerich/proyectom2:v1
